Webhook - Validate ConductorGroup is unique
openstack-k8s-operators/ironic-operator pull request #125
Opened 2023-02-16 15:49 UTC by hjensas

Reject create/update request if IronicConducts elements with duplicate ConductorGroup exists in the Ironic Spec.

Jira: OSP-22448

2023-02-16 19:35 UTC, steveb requested changes
When we finally get into the habit of writing unit tests, this sort of thing should be the first thing we test.

2023-02-16 19:35 UTC, steveb commented on api/v1beta1/ironic_webhook.go
> +        allErrs = append(allErrs, err)
This looks like spaces, not tabs

2023-02-16 20:36 UTC, hjensas commented on api/v1beta1/ironic_webhook.go
> +        allErrs = append(allErrs, err)
oops, Done.

2023-02-19 21:37 UTC, steveb approved these changes

2023-02-19 21:37 UTC, merged