Align isolated network capabilities with other operators
openstack-k8s-operators/ironic-operator pull request #159
Opened 2023-03-09 15:22 UTC by stuggi

* If needed, service pods can be attach to networks using the `networkAttachments` list in the CR. Its a list of pre-created net-attach-defs names. Per default the pods won't get attached.

```
spec:
...
      networkAttachments:
      - storage
```
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/133

* introduce externalEndpoints Parameters to configure metallb service using the pre-created metallb IPAddressPool and L2Advertisement . 

E.g. to expose the api on an internalapi network which
* should be registered as the internal endpoint
* its metallb ipaddresspool is configured in an osp-internalapi object
* and request a specific loadbalancerIP which is shared with other services (list of IPs for multi stack ipv4/ipv6)

```
...
spec:
...
      externalEndpoints:
      - endpoint: internal
        loadBalancerIPs:
        - 172.17.0.202
        ipAddressPool: osp-internalapi
        sharedIP: true
```

* removes registration of admin endpoint

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/160

2023-03-09 16:04 UTC, hjensas requested changes
Looks ok, just the nit's in the README.

2023-03-13 10:24 UTC, stuggi commented on README.md
> +The following represents an example of Glance resource that can be used
done

2023-03-13 10:24 UTC, stuggi commented on README.md
> +to trigger the service deployment, and have the internal glanceAPI endpoint
done

2023-03-13 12:08 UTC, hjensas reviewed
Thanks, looks good.

2023-03-13 12:09 UTC, hjensas approved these changes

2023-03-13 12:25 UTC, merged