CSV: Set operator-type: non-standalone
openstack-k8s-operators/ironic-operator pull request #267
Opened 2023-06-12 14:24 UTC by dprince

This should hide the ironic package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

NOTE: we may eventually make the Ironic project standalone but until then this should align ironic with other operators (hidden).

2023-06-19 19:54 UTC, steveb requested changes
This operator has a legitimate use case in standalone mode, and it only depends on the mariadb operator. As we open up to more community participation upstream I would really like that standalone story to continue, so I really don't like this change.

Downstream is another situation, but that can be a product discussion.

2023-08-02 14:38 UTC, dprince commented
@steveb Thinking a bit more about this I think it seems reasonable to me to land this. The fact is the ironic-operator isn't standalone. It has dependencies on both keystone and mariadb(Galara) operators and thus could not be installed in isolated fashion.

If we need to package Ironic as a separate product I think the way we could do that is create a meta operator that encapsulates ironic, keystone, and mariadb operators into a separate package right?

2023-08-02 19:53 UTC, steveb commented
It only requires mariadb, but this is a compelling point. We will need a new meta operator if we support deploying a standalone mode.

/lgtm
/retest

2023-08-03 21:38 UTC, steveb commented
/retest-required

2023-09-01 02:17 UTC, steveb commented
/retest-required

2023-10-02 13:46 UTC, dprince commented
/retest

2023-10-02 15:14 UTC, hjensas approved these changes

2023-10-02 16:58 UTC, merged