Remove all drac drivers from configured list
openstack-k8s-operators/ironic-operator pull request #493
Opened 2024-11-03 19:50 UTC by steveb

Dracclient has been removed from the container images[1] and ironic-conductor will not start if drac drivers are in then enabled list. This change removes them.

[1] https://github.com/openstack-k8s-operators/tcib/pull/224

2024-11-04 08:51 UTC, hjensas requested changes
Don't we want to keep the `idrac-redfish`? Only the wsman driver was removed upstream.

The `idrac-redfish` stuff is still around - https://opendev.org/openstack/ironic/src/branch/master/ironic/drivers/drac.py

2024-11-04 16:58 UTC, juliakreger commented
I concur, it likely makes sense to remove idrac-wsman items, but keep idrac-redfish around.

That mostly limits scope, and does remove the dell specifics which upstream should continue to strive for, but until the virtual media handling is sorted so just "redfish" works, I suspect it won't be entirely possible to navigate away from idrac-redfish interfaces.

2024-11-04 22:25 UTC, steveb commented
Updated to be wsman only

2024-11-04 23:17 UTC, juliakreger commented
/approve

2024-11-05 02:14 UTC, steveb reviewed
/lgtm

2024-11-05 02:14 UTC, merged

2025-01-21 17:16 UTC, hjensas commented
/cherry-pick 18.0-fr1